"""One-time import of QC Dashboard screen TSV files into PostgreSQL."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from dotenv import load_dotenv
import pandas as pd
from sqlalchemy import text

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.db import get_db_schema, get_engine
from src.screen_tables import SCREEN_DATASET_FILES, SCREEN_DATASET_TABLES, SCREEN_DATA_DIR


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--schema",
        default=get_db_schema(),
        help="Target PostgreSQL schema (default: QC_DB_SCHEMA or public).",
    )
    parser.add_argument(
        "--data-dir",
        default=str(SCREEN_DATA_DIR),
        help="Directory containing screen TSV files.",
    )
    return parser.parse_args()


def _qualified(schema: str, table_name: str) -> str:
    return f'"{schema}"."{table_name}"'


def _load_tsv(data_dir: Path, relative_tsv_path: str) -> pd.DataFrame:
    source = data_dir / relative_tsv_path
    if not source.exists():
        raise FileNotFoundError(f"Missing TSV file: {source}")
    return pd.read_csv(source, sep="\t")


def _write_table(df: pd.DataFrame, schema: str, table_name: str) -> int:
    engine = get_engine()
    df.to_sql(
        name=table_name,
        con=engine,
        schema=schema,
        if_exists="replace",
        index=False,
        method="multi",
    )

    qualified = _qualified(schema, table_name)
    with engine.begin() as conn:
        conn.execute(
            text(
                f"ALTER TABLE {qualified} "
                "ADD COLUMN \"__row_id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            )
        )

    return len(df.index)


def run_import(schema: str, data_dir: Path) -> None:
    engine = get_engine()
    with engine.begin() as conn:
        conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))

    imported_counts: dict[str, int] = {}
    for key, tsv_name in SCREEN_DATASET_FILES.items():
        table_name = SCREEN_DATASET_TABLES[key]
        df = _load_tsv(data_dir=data_dir, relative_tsv_path=tsv_name)
        imported_counts[table_name] = _write_table(df=df, schema=schema, table_name=table_name)

    print("Import complete.")
    print("Table row counts:")
    for table_name, row_count in imported_counts.items():
        print(f"- {schema}.{table_name}: {row_count}")


def main() -> None:
    load_dotenv()
    args = _parse_args()
    run_import(schema=args.schema, data_dir=Path(args.data_dir))


if __name__ == "__main__":
    main()
